---
- hosts: all
  vars:
    packages:
        - url: golang.org/x/tools/cmd/guru
        - url: github.com/motemen/gore/...
        - url: github.com/cweill/gotests/...
        - url: github.com/nsf/gocode
        - url: github.com/fatih/gomodifytags
        - url: golang.org/x/tools/gopls
  tasks:
    - name: Build src/serve.go
      command: go build -o ~/bin/serve ~/src/dot/src/serve.go
      changed_when: false

    - name: go get stuff
      command: "go get -v -ldflags='-s -w' {{ item.url }}"
      loop: "{{ packages }}"
      changed_when: false
