---
- hosts: all
  become: false
  vars:
    packages:
      - github.com/stamblerre/gocode@latest
      - golang.org/x/tools/gopls@latest
      - github.com/cweill/gotests/...
      - golang.org/x/tools/cmd/guru@latest
      - github.com/fatih/gomodifytags@latest
      - github.com/x-motemen/gore/cmd/gore@latest
  tasks:
    - name: Build src/serve.go
      command: go build -ldflags='-s -w' -o ~/bin/serve ~/src/dot/src/serve.go
      changed_when: false

    - name: Instal Go tooling
      shell: go get -u -ldflags='-s -w' {{ item }}
      loop: "{{ packages }}"
      changed_when: false
