---
- hosts: all
  vars:
    packages:
      - golang.org/x/tools/cmd/guru
#      - github.com/motemen/gore/...
      - github.com/cweill/gotests/...
      - github.com/nsf/gocode
      - github.com/fatih/gomodifytags
      - golang.org/x/tools/gopls
  tasks:
    - name: Build src/serve.go
      command: go build -ldflags='-s -w' -o ~/bin/serve ~/src/dot/src/serve.go
      changed_when: false

    - name: Instal Go tooling
      shell: go get -v -ldflags='-s -w' "{{ item }}"
      loop: "{{ packages }}"
      changed_when: false
