---
- hosts: all
  become: false
  module_defaults:
    npm:
      path: {{ ansible_facts['user_dir'] }}/.local/
      production: yes
      state: latest
  tasks:
    - name: Install formatter beautify
      npm: name=beautify

    - name: Install formatter prettier
      npm: name=prettier

    - name: Install linter stylelint
      npm: name=stylelint

    - name: Install linter textlint
      npm: name=textlint

    - name: Install linter marked
      npm: name=marked
