---
- hosts: all
  module_defaults:
    npm:
      path: /home/uki/.local/
      production: yes
      state: latest
  tasks:
    - name: Install formatter prettier
      npm: name=prettier

    - name: Install linter stylelint
      npm: name=stylelint

    - name: Install linter textlint
      npm: name=textlint

    - name: Install linter marked
      npm: name=marked
