---
- hosts: all
  become: true
  tasks:
    - name: Add docker gpg-key to Ubuntu
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add official docker-ce repository to Ubuntu
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

    - name: Add emacs repository
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Add Nodesource gpg-key to Ubuntu
      become: true
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

    - name: Add nodejs 14.x repository
      become: true
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_14.x focal main"

    - name: Install my packages
      ignore_errors: yes
      apt:
        update_cache: yes
        force_apt_get: yes
        state: latest
        name:
          - autoconf
          - build-essential
          - cargo
          - ccls
          - clang-format
          - conky-cli
          - containerd.io
          - cmake
          - curl
          - debhelper
          - dh-make-golang
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - dos2unix
          - emacs27
          - emacs27-el
          - fakeroot
          - fd-find
          - fish
          - fonts-symbola
          - fonts-terminus
          - glslang-tools
          - git
          - golang
          - grep
          - htop
          - jq
          - libtool-bin
          - lintian
          - gnutls-bin
          - mc
          - neovim
          - nodejs
          - pandoc
          - pinentry-gtk2
          - python-is-python3
          - python3-pip
          - ripgrep
          - rust-all
          - shellcheck
          - sqlite3
          - sudo
          - texinfo
          - texlive-latex-base
          - texlive-fonts-recommended
          - texlive-fonts-extra
          - texlive-latex-extra
          - tidy
          - xfonts-terminus
          - xfonts-terminus-dos
          - xfonts-terminus-oblique

    - name: Install/update vim-plug for neovim
      shell: |
          DIR="${HOME}/.local/share/nvim/site/autoload/"
          mkdir -p "${DIR}"
          curl -fLo "${DIR}/plug.vim" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
          dos2unix "${DIR}/plug.vim"
          [ -f "${DIR}/plug.vim" ] && exit 0 || exit 1
      args:
        creates: ~/.local/share/nvim/site/autoload/plug.vim
        warn: false
      become: false
