---
- hosts: all
  become: true
  vars:
    ubuntu_version: focal
    ripgrep_url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  tasks:
    - name: Add docker gpg-key to Ubuntu
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"

    - name: Add official docker-ce repository to Ubuntu
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable"

    - name: Add emacs repository
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Install my packages
      ignore_errors: yes
      apt:
        update_cache: no
        force_apt_get: yes
        state: latest
        name:
          - autoconf
          - build-essential
          - cargo
          - ccls
          - clang-format
          - clangd
          - containerd.io
          - cmake
          - curl
          - debhelper
          - docker
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - dos2unix
          - emacs28
          - emacs28-el
          - fakeroot
          - fd-find
          - fish
          - fonts-symbola
          - fonts-terminus
          - glslang-tools
          - git
          - golang-1.18-go
          - golang-1.18-src
          - golang-1.18-doc
          - golang-1.18
          - grep
          - htop
          - jq
          - keychain
          - libtool-bin
          - lintian
          - gnutls-bin
          - mc
          - pandoc
          - python-is-python3
          - python3-pip
          - shellcheck
          - shfmt
          - sqlite3
          - sudo
          - texinfo
          - texlive-latex-base
          - texlive-fonts-recommended
          - texlive-fonts-extra
          - texlive-latex-extra
          - tidy
          - vim
          - xfonts-terminus
          - xfonts-terminus-dos
          - xfonts-terminus-oblique

    - name: Install vim-plug for vim
      shell: mkdir -p ~/.vim/autoload/ && curl -sL https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim | dos2unix | tee ~/.vim/autoload/plug.vim
      args:
        creates: ~/.vim/autoload/plug.vim
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install fisher for fish
      shell: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher
      args:
        creates: ~/.config/fish/functions/fisher.fish
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install colored man pages for fish
      shell: fisher install decors/fish-colored-man
      args:
        creates: ~/.config/fish/functions/man.fish
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install docker completions for fish
      shell: fisher install lewisacidic/fish-docker
      args:
        creates: ~/.config/fish/completions/docker.fish
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install sudo completions for fish
      shell: fisher install eth-p/fish-plugin-sudo
      args:
        creates: ~/.config/fish/completions/sudo.fish
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install nvm for fish
      shell: fisher install jorgebucaran/nvm.fish
      args:
        creates: ~/.config/fish/functions/nvm.fish
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install new-ish nodejs
      shell: cd ~ && nvm install 18 && nvm use 18
      args:
        warn: false
        executable: /usr/bin/fish
      become: false

    - name: Install ripgrep from github
      shell: |
        curl -fLo /tmp/ripgrep.deb {{ ripgrep_url }} && \
        dpkg -i /tmp/ripgrep.deb  && \
        rm -f /tmp/ripgrep.deb
      args:
        creates: /usr/bin/rg
        warn: false

    - name: Update go & gofmt alternatives
      shell: |
        update-alternatives --install /usr/bin/go go /usr/lib/go-1.18/bin/go 100;
        update-alternatives --install /usr/bin/gofmt gofmt /usr/lib/go-1.18/bin/gofmt 100;
      args:
        creates:
          - /usr/bin/go
          - /usr/bin/gofmt
        warn: false
