---
- hosts: all
  become: false
  tasks:
    - name: Download emacs code
      git:
        repo: git://git.savannah.gnu.org/emacs.git
        dest: ~/src/emacs
        version: emacs-27.1

    - name: Download doom-emacs code
      git:
        repo: https://github.com/hlissner/doom-emacs
        dest: "{{ ansible_facts['user_dir'] }}/.emacs.d"
        version: develop

