---
- hosts: all
  become: false
  tasks:
    - name: Download doom-emacs code
      git:
        repo: https://github.com/hlissner/doom-emacs
        dest: "{{ ansible_facts['user_dir'] }}/.emacs.d"
        version: develop

