---
- hosts: all
  become: false
  vars:
    packages:
      - github.com/x-motemen/gore/cmd/gore@latest
      - github.com/stamblerre/gocode@latest
      - golang.org/x/tools/cmd/godoc@latest
      - golang.org/x/tools/cmd/goimports@latest
      - golang.org/x/tools/cmd/gorename@latest
      - golang.org/x/tools/cmd/guru@latest
      - github.com/cweill/gotests/gotests@latest
      - github.com/fatih/gomodifytags@latest
      - mvdan.cc/sh/v3/cmd/shfmt@latest
      #requires go 1.19 #- github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    go_opts: -ldflags='-s -w'
  tasks:
    - name: Build src/serve.go
      command: go build {{ go_opts }} -o ~/bin/serve ~/src/dot/src/serve.go
      changed_when: false

    - name: Install hugo
      command: go install {{ go_opts }} -tags extended github.com/gohugoio/hugo@latest
      changed_when: false

    - name: Instal Go tooling for wsl
      shell: go install {{ go_opts }} {{ item }}
      loop: "{{ packages }}"
      changed_when: false
