---
- hosts: all
  vars:
      gsettings:
        - name: 'org.gnome.login-screen'
          var: 'enable-fingerprint-authentication'
          val: 'false'
        - name: 'org.gnome.login-screen'
          var: 'enable-smartcard-authentication'
          val: 'false'
        - name: 'org.gnome.login-screen'
          var: 'disable-user-list'
          val: 'true'
        - name: 'org.gnome.books'
          var: 'night-mode'
          val: 'true'
        - name: 'org.gnome.Evince.Default'
          var: 'show-sidebar'
          val: 'false'
        - name: 'com.ubuntu.touch.network'
          var: 'gps'
          val: 'false'
        - name: 'org.gnome.desktop.lockdown'
          var: 'disable-user-switching'
          val: 'true'
        - name: 'org.gnome.desktop.lockdown'
          var: 'disable-command-line'
          val: 'true'
        - name: 'org.gnome.desktop.peripherals.keyboard'
          var: 'numlock-state'
          val: 'true'
        - name: 'org.gnome.desktop.background'
          var: 'picture-uri'
          val: 'none'
        - name: 'org.gnome.desktop.screensaver'
          var: 'picture-uri'
          val: 'none'
        - name: 'org.gnome.gnome-flashback'
          var: 'root-background'
          val: 'false'
  tasks:
    - name: Setup gsettings
      command: "gsettings set {{ item['name'] }} {{ item['var'] }} {{ item['val'] }}"
      loop: "{{ gsettings }}"
      ignore_errors: yes
