---
- hosts: all
  vars:
    home: "{{ ansible_facts['user_dir'] }}/"
    hidden_dir: "{{ home }}src/dot/hidden/"
    files_dir: "{{ home }}src/dot/files/"
  module_defaults:
    file:
      state: link
      force: yes
  tasks:
    - name: Gather a list of config files
      find:
        paths: "{{ hidden_dir }}"
        recurse: yes
      register: hidden_files

    - name: Create missing hidden dirs
      shell: "mkdir -p $(dirname {{ item['path']|replace(hidden_dir, home+'.') }})"
      loop: "{{ hidden_files.files }}"
      args:
        warn: false

    - name: Link config files to home
      file:
        src: "{{ item['path'] }}"
        dest: "{{ item['path']|replace(hidden_dir, home+'.') }}"
        state: link
      loop: "{{ hidden_files.files }}"

    - name: Gather a list of regular files
      find:
        paths: "{{ files_dir }}"
        recurse: yes
      register: files

    - name: Create missing regular dirs
      shell: "mkdir -p $(dirname {{ item['path']|replace(files_dir, home) }})"
      loop: "{{ files.files }}"
      args:
        warn: false

    - name: Link regular files to home
      file:
        src: "{{ item['path'] }}"
        dest: "{{ item['path']|replace(files_dir, home) }}"
        state: link
      loop: "{{ files.files }}"

    - name: Get windows USERPROFILE
      shell: "{{ files_dir }}/bin/winenv.sh -p USERPROFILE"
      register: userprofile

    - name: Link to windows USERPROFILE
      file:
        src: "{{ userprofile.stdout }}"
        dest: "{{ home }}/mnt"
        state: link

    - name: Create .m2 dir in windows
      file:
        path: "{{ userprofile.stdout }}/.m2"
        state: directory

    - name: Copy a new version of .gitconfig to windows
      copy:
        src: "{{ hidden_dir }}/gitconfig"
        dest: "{{ userprofile.stdout }}/.gitconfig"
        force: yes

