---
- hosts: all
  vars:
    home: "{{ ansible_facts['user_dir'] }}/"
    hidden_dir: "{{ home }}src/dot/hidden/"
    files_dir: "{{ home }}src/dot/files/"
    mnt: "/mnt/c/Users/lukas"
  module_defaults:
    file:
      state: link
      force: yes
  tasks:
    - name: Gather a list of config files
      find:
        paths: "{{ hidden_dir }}"
        recurse: yes
      register: hidden_files

    - name: Create missing hidden dirs
      shell: "mkdir -p $(dirname {{ item['path']|replace(hidden_dir, home+'.') }})"
      loop: "{{ hidden_files.files }}"
      args:
        warn: false

    - name: Link config files to home
      file:
        src: "{{ item['path'] }}"
        dest: "{{ item['path']|replace(hidden_dir, home+'.') }}"
        state: link
      loop: "{{ hidden_files.files }}"

    - name: Gather a list of regular files
      find:
        paths: "{{ files_dir }}"
        recurse: yes
      register: files

    - name: Create missing regular dirs
      shell: "mkdir -p $(dirname {{ item['path']|replace(files_dir, home) }})"
      loop: "{{ files.files }}"
      args:
        warn: false

    - name: Link regular files to home
      file:
        src: "{{ item['path'] }}"
        dest: "{{ item['path']|replace(files_dir, home) }}"
        state: link
      loop: "{{ files.files }}"

    - name: Link to windows USERPROFILE
      file:
        src: "{{ mnt }}"
        dest: "{{ home }}/mnt"
        state: link

    - name: Link to windows .m2
      file:
        src: "{{ mnt }}/.m2"
        dest: "{{ home }}/.m2"
        state: link

    - name: Copy .gitconfig to windows
      copy:
        src: "{{ hidden_dir }}/gitconfig"
        dest: "{{ mnt }}/.gitconfig"
        force: yes

