---
- hosts: all
  become: false
  vars:
    home: "{{ ansible_facts['user_dir'] }}/"
    hidden_dir: "{{ home }}src/dot/hidden/"
    files_dir: "{{ home }}src/dot/files/"
    src_dir: "{{ home }}src/dot/src/"
  module_defaults:
    file:
      state: link
      force: true
  tasks:
    - name: Gather a list of config files
      find:
        paths: "{{ hidden_dir }}"
        recurse: true
      register: hidden_files

    - name: Create missing hidden dirs
      file:
        path: "{{ item['path']|replace(hidden_dir, home+'.')|dirname }}"
        state: directory
        force: false
      loop: "{{ hidden_files.files }}"

    - name: Link config files to home
      file:
        src: "{{ item['path'] }}"
        dest: "{{ item['path']|replace(hidden_dir, home+'.') }}"
      loop: "{{ hidden_files.files }}"

    - name: Gather a list of regular files
      find:
        paths: "{{ files_dir }}"
        recurse: true
      register: files

    - name: Create missing regular dirs
      file:
        path: "{{ item['path']|replace(files_dir, home)|dirname }}"
        state: directory
        force: false
      loop: "{{ files.files }}"

    - name: Link regular files to home
      file:
        src: "{{ item['path'] }}"
        dest: "{{ item['path']|replace(files_dir, home) }}"
      loop: "{{ files.files }}"

    - name: Get windows USERPROFILE
      shell: "{{ files_dir }}bin/winenv.sh -p USERPROFILE"
      register: userprofile

    - name: Link to windows USERPROFILE
      file:
        src: "{{ userprofile.stdout }}"
        dest: "{{ home }}mnt"

    - name: Create .m2 dir in windows
      file:
        path: "{{ userprofile.stdout }}/.m2"
        state: directory
        force: false

    - name: Link to windows .m2 to wsl
      file:
        src: "{{ userprofile.stdout }}/.m2"
        dest: "{{ home }}.m2"

    - name: Copy a new version of .gitconfig to windows
      copy:
        src: "{{ hidden_dir }}gitconfig"
        dest: "{{ userprofile.stdout }}/.gitconfig"
        force: true

    - name: Ensure .gitconfig.local is present
      file:
        dest: "{{ userprofile.stdout }}/.gitconfig.local"
        state: touch

    - name: Link .gitconfig.local from windows if exists
      file:
        src: "{{ userprofile.stdout }}/.gitconfig.local"
        dest: "{{ home }}.gitconfig.local"

    - name: Ensure .local.fish file on windows
      copy:
        src: "{{ src_dir }}dot.local.fish.example"
        dest: "{{ userprofile.stdout }}/.local.fish"

    - name: Link .local.fish from windows if exists
      file:
        src: "{{ userprofile.stdout }}/.local.fish"
        dest: "{{ home }}.local.fish"

    - name: Link /etc/wsl.conf
      copy:
        src: "{{ src_dir }}wsl.conf"
        dest: "/etc/wsl.conf"
        mode: '644'
      become: true
