---
- hosts: all
  become: true
  vars:
    ubuntu_version: focal
    ripgrep_url: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  tasks:
    - name: Add docker gpg-key to Ubuntu
      apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"

    - name: Add official docker-ce repository to Ubuntu
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable"

    - name: Add emacs repository
      apt_repository:
        repo: ppa:kelleyk/emacs

    - name: Install my packages
      ignore_errors: yes
      apt:
        update_cache: no
        force_apt_get: yes
        state: latest
        name:
          - autoconf
          - build-essential
          - cargo
          - ccls
          - clang-format
          - clangd
          - containerd.io
          - cmake
          - curl
          - debhelper
          - docker
          - docker-ce
          - docker-ce-cli
          - docker-compose
          - dos2unix
          - emacs28
          - emacs28-el
          - fakeroot
          - fd-find
          - fish
          - fonts-symbola
          - fonts-terminus
          - glslang-tools
          - git
          - golang-1.18-go
          - golang-1.18-src
          - golang-1.18-doc
          - golang-1.18
          - grep
          - htop
          - jq
          - keychain
          - libtool-bin
          - lintian
          - gnutls-bin
          - mc
          - openjdk-17-jdk
          - pandoc
          - python-is-python3
          - python3-pip
          - shellcheck
          - sqlite3
          - sudo
          - texinfo
          - texlive-latex-base
          - texlive-fonts-recommended
          - texlive-fonts-extra
          - texlive-latex-extra
          - tidy
          - vim
          - xfonts-terminus
          - xfonts-terminus-dos
          - xfonts-terminus-oblique

    - name: Install ripgrep from github
      shell: |
        curl -fLo /tmp/ripgrep.deb {{ ripgrep_url }} && \
        dpkg -i /tmp/ripgrep.deb  && \
        rm -f /tmp/ripgrep.deb
      args:
        creates: /usr/bin/rg
        warn: false

    - name: Don't overwrite with ubuntu version
      shell: echo "ripgrep hold" | dpkg --set-selections
      args:
        warn: false

    - name: Update go & gofmt alternatives
      shell: |
        update-alternatives --install /usr/bin/go go /usr/lib/go-1.18/bin/go 100;
        update-alternatives --install /usr/bin/gofmt gofmt /usr/lib/go-1.18/bin/gofmt 100;
      args:
        creates:
          - /usr/bin/go
          - /usr/bin/gofmt
        warn: false
