---
- hosts: all
  become: true
  tasks:
    - name: Add docker gpg-key to Ubuntu
      shell:
        install -m 0755 -d /etc/apt/keyrings && \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc && \
        chmod a+r /etc/apt/keyrings/docker.asc

    - name: Add official docker-ce repository to Ubuntu
      shell: |
        sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
        Types: deb
        URIs: https://download.docker.com/linux/ubuntu
        Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
        Components: stable
        Architectures: $(dpkg --print-architecture)
        Signed-By: /etc/apt/keyrings/docker.asc
        EOF

    - name: Install my packages
      ignore_errors: yes
      apt:
        update_cache: no
        force_apt_get: yes
        state: latest
        name:
          - autoconf
          - build-essential
          - cargo
          - clang-format
          - clangd
          - cmake
          - curl
          - debhelper
          - docker-ce
          - docker-ce-cli
          - dos2unix
          - fakeroot
          - fdclone
          - fd-find
          - fish
          - flatpak
          - fonts-symbola
          - fonts-terminus
          - glslang-tools
          - git
          - golang
          - grep
          - htop
          - jq
          - keychain
          - libtool-bin
          - lintian
          - gnutls-bin
          - mc
          - openjdk-25-jdk
          - pandoc
          - python-is-python3
          - python3-full
          - python3-pip
          - python3-venv
          - ripgrep
          - shellcheck
          - sqlite3
          - sudo
          - texinfo
          - texlive-latex-base
          - texlive-fonts-recommended
          - texlive-fonts-extra
          - texlive-latex-extra
          - tidy
          - vim

    - name: Install Emacs from flatpack
      shell: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnu.emacs
