---
- hosts: all
  tasks:
    - name: Install stuff
      shell: |
        python3 -m venv ~/.venv
        ln -s ~/.venv/bin/python3 ~/bin/python3
        ln -s ~/.venv/bin/python ~/bin/python
        ln -s ~/.venv/bin/pip ~/bin/pip
        ~/.venv/bin/pip install pytest
        ~/.venv/bin/pip install nose
        ~/.venv/bin/pip install black
        ~/.venv/bin/pip install pyflakes
        ~/.venv/bin/pip install isort
        ~/.venv/bin/pip install pipenv
        curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | ~/.venv/bin/python
        ln -s ~/.cask/bin/cask ~/bin/cask
