---
- hosts: all
  module_defaults:
    pip:
      extra_args: --user
      state: latest
  tasks:
    - name: Install pytest
      pip: name=pytest
    - name: Install nose
      pip: name=nose
    - name: Install black
      pip: name=black
    - name: Install pyflakes
      pip: name=pyflakes
    - name: Install isort
      pip: name=isort
    - name: Install pipenv
      pip: name=pipenv
    - name: Install Cask
      shell: |
          curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
          ln -s ~/.cask/bin/cask ~/bin/cask
      args:
          warn: no
          creates: ~/bin/cask
