---
- hosts: all
  become: false
  vars:
    home_dirs:
      - bin
      - pub
      - src
      - incoming
      - .cache
      - .templates
      - .local/share/info
      - org
  tasks:
    - name: Create home directories
      file:
        path: "{{ ansible_facts['user_dir'] }}/{{ item }}"
        state: directory
      loop: "{{ home_dirs }}"

    - name: Get windows USERPROFILE
      shell: "{{ ansible_facts['user_dir'] }}/src/dot/files/bin/winenv.sh -p USERPROFILE"
      register: userprofile

    - name: Fetch my GPG keys for windows
      git:
        repo: git@github.com:ukaszg/_gnupg.git
        dest: "{{ userprofile.stdout }}/.gnupg"
        executable: /usr/bin/git
        clone: yes
        update: yes
        version: master

    - name: Link windows GPG keys to WSL
      file:
        src: "{{ userprofile.stdout }}/.gnupg"
        dest: "{{ ansible_facts['user_dir'] }}/.gnupg"
        state: link
        force: true

    - name: who am I?
      shell: "whoami"
      register: whoami

    - name: Get path to fish executable
      shell: "command -v fish"
      register: fish_path

    - name: Set fish as my default shell
      user:
        name: "{{ whoami.stdout }}"
        shell: "{{ fish_path.stdout }}"
      become: true

    - name: Add me to a docker group
      user:
        name: "{{ whoami.stdout }}"
        groups: docker
        append: yes
      become: true

