---
- hosts: all
  become: false
  vars:
    home_dirs:
      - bin
      - m
      - pic/wp
      - pub
      - vid
      - src
      - incoming
      - .cache
      - .templates
      - .local/share/info
      - org
  tasks:
    - name: Create home directories
      file:
        path: "{{ ansible_facts['user_dir'] }}/{{ item }}"
        state: directory
      loop: "{{ home_dirs }}"

    - name: Fetch my GPG keys
      git:
          repo: git@github.com:ukaszg/_gnupg.git
          dest: "{{ ansible_facts['user_dir'] }}/.gnupg"
          clone: yes
          update: yes

    - name: who am I?
      shell: "whoami"
      register: whoami

    - name: Set fish as my default shell
      user:
        name: "{{ whoami }}"
        shell: /usr/bin/fish
      become: true

    - name: Add me to a docker group
      user:
        name: "{{ whoami }}"
        groups: docker
        append: yes
      become: true
