---
- hosts: all
  tasks:
    - name: Fetch my GPG keys
      git:
          repo: git@github.com:ukaszg/_gpg.git
          dest: ~/.gpg
          clone: yes
          update: yes

    - name: Set fish as my default shell
      user:
        name: uki
        shell: /usr/bin/fish
      become: true

    - name: Add me to a docker group
      user:
        name: uki
        groups: docker
        append: yes
      become: true
